import React from "react";
import FeatureCard from "./FeatureCard";

const OverviewSection = () => {
    return (
        <section id="features" className="flex flex-col items-center relative w-full">
            <div className="mt-24 max-w-full text-center px-[28px] md:px-0 md:w-[717px] max-md:mt-10 z-[20]">
                <h3 className="text-xl md:text-2xl font-semibold leading-none text-yellow-400 font-['Amble'] md:font-['Jost'] max-md:max-w-full">
                    Overview of MiniRipple
                </h3>
                <h2 className="mt-4 text-[24px] md:text-[30px] tracking-normal md:tracking-[-1.5px] lg:text-[40px] lg:tracking-normal text-blue-200 font-['Jost'] font-semibold md:font-['Amble'] md:font-bold lg:font-['Anton'] lg:font-normal max-md:max-w-full leading-[28px] md:leading-relaxed">
                    Protect Your Business from Malicious Traffic, Bots, and Click Fraud
                </h2>
                <p className="mt-4 text-base text-slate-400 font-['Jost'] max-md:max-w-full">
                    MiniRipple provides robust security solutions to safeguard your online
                    presence. By detecting and mitigating harmful activity, it ensures
                    your digital assets remain secure and optimized.
                </p>
            </div>

            <div className="flex flex-wrap gap-6 items-start justify-center md:mt-14 max-md:mt-4 max-md:max-w-full z-[40]">
                
                <FeatureCard
                    icon="/landing/overview-1.png"
                    title="Advanced Threat Detection"
                    description="Identifies and blocks suspicious traffic in real time, preventing unauthorized access, mitigating potential cyber threats, and ensuring the security of your network. By continuously analyzing patterns and anomalies, it detects malicious activities such as DDoS attacks, brute-force."
                    link="/dashboard/threat-detection"
                />

                <FeatureCard
                    icon="/landing/overview-2.png"
                    title="Bot Prevention"
                    description="Protects your website and ads from automated bot attacks by detecting and blocking malicious traffic in real time. This helps prevent fraudulent clicks, credential stuffing, data scraping, and other harmful activities that can impact your site's performance and advertising ROI."
                    link="/dashboard/bot-prevention"
                />

                <FeatureCard
                    icon="/landing/overview-3.png"
                    title="Click Fraud Mitigation"
                    description="Prevents fraudulent ad clicks to optimize marketing ROI by identifying and blocking invalid traffic generated by bots, click farms, and other malicious sources. This ensures that your advertising budget is spent on genuine user engagement rather than wasted on fraudulent activity."
                    link="/dashboard/fraud-mitigation"
                />
            </div>
            <div className="absolute w-[684px] h-[684px] shrink-0 rounded-full bg-[#ffc10780] blur-[250px] right-[-700px] top-[-300px] z-[0]"></div>
            <div className="absolute left-[-350px] top-[-650px] z-[0]">
                <svg xmlns="http://www.w3.org/2000/svg" width="865" height="1746" viewBox="0 0 865 1746" fill="none">
                    <g filter="url(#filter0_f_1_1603)">
                        <path d="M-508 1245V501.17C-508 500.316 -506.999 499.855 -506.35 500.41L363.941 1244.24C364.647 1244.84 364.22 1246 363.291 1246H-507C-507.552 1246 -508 1245.55 -508 1245Z" fill="#FFC107" fillOpacity="0.5" />
                    </g>
                    <defs>
                        <filter id="filter0_f_1_1603" x="-1008" y="0.168457" width="1872.29" height="1745.83" filterUnits="userSpaceOnUse" colorInterpolationFilters="sRGB">
                            <feFlood floodOpacity="0" result="BackgroundImageFix" />
                            <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
                            <feGaussianBlur stdDeviation="250" result="effect1_foregroundBlur_1_1603" />
                        </filter>
                    </defs>
                </svg>
            </div>
        </section>
    );
};

export default OverviewSection;
